### ISSUE TITLE
Oak & Spruce Leaves LootTable Broken in 1.20.1

### ISSUE THREAD

**Issue by Gryzle** [maxheyn/miniblock_traders#2]
Oak & Spruce leaves' loot tables produce an error in the console and fail to drop any items.

**Comment by psystarmie** [comment]
installed this plug in and had the same issue, was a fix ever found or anything?

**Comment by maxheyn** [comment]
Hello, thanks for reporting this issue. I've finally had time to come around and work on this again.

This should be fixed in v.3.1.0

https://github.com/maxheyn/miniblock_traders/releases/tag/v.3.1.0
